name: Compile Flutter app

# Controls when the action will run. 
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JAVA for Android
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Set up Flutter and Dart
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Download required packages
      run: |
        cd grove_app
        flutter pub get
    - name: Build Android app
      run: |
        cd grove_app
        flutter build appbundle
    - name: Build iOS App
      run: |
        cd grove_app
        flutter build ios --release --no-codesign
